spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BankingTrans?createDatabaseIfNotExist=true
    username: root
    password: Naveen@8123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8089

logging:
  level:
    org.springframework.security: DEBUG