spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/BankingTrans?createDatabaseIfNotExist=true
    url: jdbc:mysql://mysql-docker:3306/banking_trans?serverTimezone=UTC
    username: root
    password: root
#    password: Naveen@8123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
#server:
#  port: 8089

logging:
  level:
    org.springframework.security: DEBUG

# mysql-docker = name of docker container